fieldLayouts:
  a30b6fb7-70ff-405b-aeb5-fe6a1028d953:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 154e9917-9727-4dc3-a77d-868e63738f9d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3ac8b014-7244-4a41-a1c5-3bdc2abf9797
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: b8bcf4ef-f467-4195-8da0-d42ba9139777 # Products
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
