fieldLayouts:
  a30b6fb7-70ff-405b-aeb5-fe6a1028d953:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 154e9917-9727-4dc3-a77d-868e63738f9d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8f061a1b-fb42-4a05-a034-195f03948d46 # Brand
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d54854b8-d8a7-450f-933f-91f4c1e3d4f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 11b72207-e6a8-4c72-ab25-3984e82b8c78 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32b08055-92e3-4eb4-8bad-815c3eb53b55
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d588545b-bda8-4d87-9dee-87591eb555f4 # Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40aeab21-4d06-4a67-9b8a-c95e57d57ed8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a04d705-51ad-4446-8e79-4f494f459b9a # Price
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 725749a6-3c7f-40bf-ab8e-d52b5e714c0d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9c4cb7e5-3ac4-4674-b03f-3eccbe1aae2c # Stock
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b2179bf-e96b-4c95-8342-615ca2af2909
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5dc40482-f9c7-4597-a9e0-aded69a3b660 # Warranty
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ace91d42-5763-40ec-8990-dde5d7f0e695
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3ac8b014-7244-4a41-a1c5-3bdc2abf9797
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: b8bcf4ef-f467-4195-8da0-d42ba9139777 # Products
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
