fieldLayouts:
  c85bd098-bf32-4465-9a73-5516e6bf92d4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c4f6c27e-af73-4db8-b7f2-3b77bfd37076
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: c0ca83f4-c074-4eb1-897b-9de1b23e07b4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 70d6c1a9-d38e-4545-bab7-25f68464531f
        userCondition: null
fs: assets
handle: furnitureAssets
name: 'Furniture Assets'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: assets
transformSubpath: ''
