columnSuffix: cfucgyiu
contentColumnType: string(100)
fieldGroup: e92e414f-7845-449e-8125-dad30e6a44a3 # Common
handle: colorName
instructions: null
name: 'Color Name'
searchable: false
settings:
  byteLimit: null
  charLimit: 25
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
