columnSuffix: oxevzcjc
contentColumnType: string(15)
fieldGroup: e92e414f-7845-449e-8125-dad30e6a44a3 # Common
handle: material
instructions: null
name: Material
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - label
          - Fabric
        -
          - value
          - fabric
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Leather
        -
          - value
          - leather
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Solid Walnut Wood'
        -
          - value
          - walnutVeneer
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Solid Rubber Wood'
        -
          - value
          - solidRubberWood
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
