columnSuffix: ukwfhcrj
contentColumnType: boolean
fieldGroup: e92e414f-7845-449e-8125-dad30e6a44a3 # Common
handle: spotlight
instructions: null
name: Spotlight
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
