defaultPlacement: beginning
enableVersioning: true
handle: brands
name: Brands
propagationMethod: all
siteSettings:
  f8d9a7b1-d152-4891-b80e-8f3af70f868b: # FurnDeco
    enabledByDefault: true
    hasUrls: true
    template: brands/_entry
    uriFormat: 'brands/{slug}'
structure:
  maxLevels: null
  uid: cb102f8b-50cc-4a18-b589-ae3891301f90
type: structure
