defaultPlacement: beginning
enableVersioning: true
handle: categories
name: Categories
propagationMethod: all
siteSettings:
  f8d9a7b1-d152-4891-b80e-8f3af70f868b: # FurnDeco
    enabledByDefault: true
    hasUrls: true
    template: categories/_entry
    uriFormat: 'categories/{slug}'
structure:
  maxLevels: null
  uid: ee8b2fed-7ba9-4d8e-862b-efa102b7746d
type: structure
