defaultPlacement: end
enableVersioning: true
handle: favourites
name: Favourites
propagationMethod: all
siteSettings:
  f8d9a7b1-d152-4891-b80e-8f3af70f868b: # FurnDeco
    enabledByDefault: true
    hasUrls: true
    template: favourites/_entry
    uriFormat: 'favourites/{slug}'
type: channel
